export const DEMO_PRODUCT_TAG = 'client-demo-product';

const clothingStock = [
  ['S', 8],
  ['M', 12],
  ['L', 10],
  ['XL', 7],
  ['XXL', 5],
];

const generousClothingStock = [
  ['S', 10],
  ['M', 14],
  ['L', 12],
  ['XL', 9],
  ['XXL', 6],
];

const hijabStock = [['Free Size', 28]];

function sizes(stockRows) {
  return stockRows.map(([name, stock]) => ({ name, stock, active: true }));
}

function tags(values) {
  return [DEMO_PRODUCT_TAG, ...values];
}

export const demoProducts = [
  {
    name: 'Rose Pink Embroidered Churidar Set',
    slug: 'rose-pink-embroidered-churidar-set',
    skuPrefix: 'AMR-CHU-ROSE',
    mainCategorySlug: 'ethnic-wear',
    subcategorySlug: 'churidar-sets',
    productType: 'Churidar Sets',
    style: 'Ethnic',
    fabric: 'Rayon',
    occasion: 'Festive',
    colourName: 'Rose Pink',
    colourHex: '#C68C7B',
    regularPrice: 2899,
    salePrice: 2399,
    stockRows: clothingStock,
    featured: true,
    newArrival: true,
    bestSeller: false,
    tags: tags(['ethnic', 'embroidered', 'festive', 'premium', 'new-arrival']),
    shortDescription: 'A graceful rose pink churidar set finished with delicate embroidery for festive and family occasions.',
    description:
      'Designed for celebrations that call for comfort and polish, this rose pink churidar set pairs soft drape with refined embroidery. The silhouette keeps movement easy while the tonal detailing gives the outfit a dressed-up finish for festive visits, intimate functions and elegant day events.',
    fabricDetails: 'Soft rayon blend with embroidered accents and a smooth lining feel.',
    fit: 'Regular kurta fit with comfortable churidar styling.',
    careInstructions: 'Dry clean preferred. Store folded away from direct sunlight.',
    metaTitle: 'Rose Pink Embroidered Churidar Set',
    metaDescription: 'Shop a rose pink embroidered churidar set with festive detailing from Amorah.',
  },
  {
    name: 'Midnight Blue Partywear Gown',
    slug: 'midnight-blue-partywear-gown',
    skuPrefix: 'AMR-GWN-MID',
    mainCategorySlug: 'ethnic-wear',
    subcategorySlug: 'gowns',
    productType: 'Gowns',
    style: 'Partywear',
    fabric: 'Rayon',
    occasion: 'Party',
    colourName: 'Midnight Blue',
    colourHex: '#24324F',
    regularPrice: 5199,
    salePrice: 4599,
    stockRows: clothingStock,
    featured: true,
    newArrival: false,
    bestSeller: true,
    tags: tags(['partywear', 'gown', 'occasion', 'premium', 'best-seller']),
    shortDescription: 'A flowing midnight blue gown made for evening celebrations and polished party dressing.',
    description:
      'This midnight blue partywear gown brings together a fluid fall, shaped waist and subtle surface sheen for a refined evening look. Style it with metallic heels and delicate jewellery for receptions, dinners and special occasions where a clean statement is enough.',
    fabricDetails: 'Smooth woven fabric with a soft sheen and structured drape.',
    fit: 'Fitted through the bodice with a graceful flared skirt.',
    careInstructions: 'Dry clean only. Steam gently from the reverse side.',
    metaTitle: 'Midnight Blue Partywear Gown',
    metaDescription: 'A premium midnight blue partywear gown for evening occasions.',
  },
  {
    name: 'Sage Green Western Co-ord Set',
    slug: 'sage-green-western-co-ord-set',
    skuPrefix: 'AMR-COR-SGE',
    mainCategorySlug: 'western-wear',
    subcategorySlug: 'western-co-ord-sets',
    productType: 'Western Co-ord Sets',
    style: 'Western',
    fabric: 'Linen',
    occasion: 'Casual',
    colourName: 'Sage Green',
    colourHex: '#78866B',
    regularPrice: 2699,
    salePrice: 2199,
    stockRows: generousClothingStock,
    featured: true,
    newArrival: true,
    bestSeller: false,
    tags: tags(['western', 'co-ord', 'casual', 'premium', 'new-arrival']),
    shortDescription: 'A relaxed sage green co-ord set with a fresh, put-together feel for everyday outings.',
    description:
      'Made for easy styling, this sage green co-ord set balances a clean western silhouette with breathable comfort. The matching top and bottom create an instantly complete outfit for cafe plans, college days, travel looks and casual office dressing.',
    fabricDetails: 'Linen blend with a breathable hand feel and soft texture.',
    fit: 'Relaxed coordinated fit with easy movement.',
    careInstructions: 'Machine wash cold on gentle cycle. Line dry in shade.',
    metaTitle: 'Sage Green Western Co-ord Set',
    metaDescription: 'Shop a sage green western co-ord set for everyday polished styling.',
  },
  {
    name: 'Floral Knee-Length Casual Top',
    slug: 'floral-knee-length-casual-top',
    skuPrefix: 'AMR-TOP-FLR',
    mainCategorySlug: 'western-wear',
    subcategorySlug: 'knee-length-tops',
    productType: 'Knee-Length Tops',
    style: 'Casual',
    fabric: 'Cotton',
    occasion: 'Everyday',
    colourName: 'Ivory Floral',
    colourHex: '#FAF6EE',
    regularPrice: 1399,
    salePrice: 1099,
    stockRows: generousClothingStock,
    featured: false,
    newArrival: true,
    bestSeller: false,
    tags: tags(['casual', 'floral', 'western', 'everyday', 'new-arrival']),
    shortDescription: 'A breezy knee-length top with a soft floral print for easy everyday dressing.',
    description:
      'This floral knee-length casual top is light, feminine and simple to pair with jeans or leggings. The easy length gives comfortable coverage while the floral artwork keeps the look fresh for day plans, errands and relaxed get-togethers.',
    fabricDetails: 'Soft cotton fabric with a breathable everyday finish.',
    fit: 'Easy straight fit with knee-length coverage.',
    careInstructions: 'Machine wash cold with like colours. Do not bleach.',
    metaTitle: 'Floral Knee-Length Casual Top',
    metaDescription: 'A soft floral knee-length top for casual Amorah outfits.',
  },
  {
    name: 'Black Ribbed Short Top',
    slug: 'black-ribbed-short-top',
    skuPrefix: 'AMR-SHT-BLK',
    mainCategorySlug: 'western-wear',
    subcategorySlug: 'short-tops',
    productType: 'Short Tops',
    style: 'Contemporary',
    fabric: 'Cotton',
    occasion: 'Casual',
    colourName: 'Black',
    colourHex: '#181513',
    regularPrice: 1199,
    salePrice: 899,
    stockRows: generousClothingStock,
    featured: false,
    newArrival: false,
    bestSeller: true,
    tags: tags(['western', 'casual', 'ribbed', 'black', 'best-seller']),
    shortDescription: 'A fitted black ribbed short top that works as a clean base for everyday western looks.',
    description:
      'A wardrobe essential with a neat ribbed texture, this black short top is made for pairing with denim, skirts and layered shirts. The close fit keeps the look sharp while the soft stretch makes it comfortable for repeat wear.',
    fabricDetails: 'Cotton-rich rib fabric with gentle stretch.',
    fit: 'Fitted short length.',
    careInstructions: 'Machine wash cold. Dry flat to retain shape.',
    metaTitle: 'Black Ribbed Short Top',
    metaDescription: 'A black ribbed short top for casual western styling.',
  },
  {
    name: 'White Oversized Shirt for Girls',
    slug: 'white-oversized-shirt-for-girls',
    skuPrefix: 'AMR-SHR-WHT',
    mainCategorySlug: 'western-wear',
    subcategorySlug: 'shirts-for-girls',
    productType: 'Shirts for Girls',
    style: 'Western',
    fabric: 'Cotton',
    occasion: 'Workwear',
    colourName: 'White',
    colourHex: '#FFFDF8',
    regularPrice: 1499,
    salePrice: 1199,
    stockRows: clothingStock,
    featured: false,
    newArrival: true,
    bestSeller: false,
    tags: tags(['western', 'shirt', 'oversized', 'workwear', 'new-arrival']),
    shortDescription: 'A crisp white oversized shirt with relaxed structure for smart casual styling.',
    description:
      'This oversized white shirt brings a clean, confident look to everyday wardrobes. Wear it buttoned, layered over a top or tucked into denim for a smart casual outfit that feels effortless without looking unfinished.',
    fabricDetails: 'Crisp cotton poplin with a smooth finish.',
    fit: 'Oversized fit with dropped shoulders.',
    careInstructions: 'Machine wash cold. Warm iron if needed.',
    metaTitle: 'White Oversized Shirt for Girls',
    metaDescription: 'A crisp oversized white shirt for girls from Amorah.',
  },
  {
    name: 'High-Waist Straight-Fit Blue Jeans',
    slug: 'high-waist-straight-fit-blue-jeans',
    skuPrefix: 'AMR-JNS-BLU',
    mainCategorySlug: 'western-wear',
    subcategorySlug: 'jeans',
    productType: 'Jeans',
    style: 'Western',
    fabric: 'Denim',
    occasion: 'Casual',
    colourName: 'Medium Blue',
    colourHex: '#4A6F9F',
    regularPrice: 2199,
    salePrice: 1799,
    stockRows: clothingStock,
    featured: false,
    newArrival: false,
    bestSeller: true,
    tags: tags(['western', 'jeans', 'denim', 'casual', 'best-seller']),
    shortDescription: 'High-waist blue jeans with a straight fit for a clean, everyday denim look.',
    description:
      'These high-waist straight-fit blue jeans are designed for repeat styling with shirts, tops and kurtis. The balanced straight leg keeps the silhouette current, while the medium blue wash makes the pair easy to dress up or down.',
    fabricDetails: 'Medium-weight denim with structured comfort.',
    fit: 'High waist with a straight-leg fit.',
    careInstructions: 'Wash inside out with similar colours. Avoid harsh bleach.',
    metaTitle: 'High-Waist Straight-Fit Blue Jeans',
    metaDescription: 'High-waist straight-fit blue jeans for everyday Amorah styling.',
  },
  {
    name: 'Premium Black Jersey Hijab',
    slug: 'premium-black-jersey-hijab',
    skuPrefix: 'AMR-HJB-BLK',
    mainCategorySlug: 'hijabs',
    subcategorySlug: 'jersey-hijabs',
    productType: 'Jersey Hijabs',
    style: 'Hijab',
    fabric: 'Jersey',
    occasion: 'Everyday',
    colourName: 'Black',
    colourHex: '#181513',
    regularPrice: 799,
    salePrice: 649,
    stockRows: hijabStock,
    featured: true,
    newArrival: false,
    bestSeller: true,
    tags: tags(['hijab', 'jersey', 'premium', 'black', 'best-seller']),
    shortDescription: 'A premium black jersey hijab with soft stretch and everyday drape.',
    description:
      'A versatile essential, this premium black jersey hijab offers a smooth drape and comfortable stretch for all-day wear. The fabric stays easy to style, making it ideal for daily outfits, travel and polished modest looks.',
    fabricDetails: 'Soft stretch jersey with a smooth matte finish.',
    fit: 'Free size with easy drape.',
    careInstructions: 'Hand wash or gentle machine wash. Dry in shade.',
    metaTitle: 'Premium Black Jersey Hijab',
    metaDescription: 'A premium black jersey hijab with soft everyday drape.',
  },
  {
    name: 'Dusty Rose Shimmer Hijab',
    slug: 'dusty-rose-shimmer-hijab',
    skuPrefix: 'AMR-HJB-DRS',
    mainCategorySlug: 'hijabs',
    subcategorySlug: 'shimmer-hijabs',
    productType: 'Shimmer Hijabs',
    style: 'Hijab',
    fabric: 'Shimmer',
    occasion: 'Party',
    colourName: 'Dusty Rose',
    colourHex: '#C68C7B',
    regularPrice: 999,
    salePrice: 849,
    stockRows: hijabStock,
    featured: false,
    newArrival: true,
    bestSeller: false,
    tags: tags(['hijab', 'shimmer', 'partywear', 'premium', 'new-arrival']),
    shortDescription: 'A dusty rose shimmer hijab with a refined glow for festive and evening looks.',
    description:
      'This dusty rose shimmer hijab adds a soft luminous finish without feeling loud. The graceful colour pairs beautifully with ethnic and occasionwear outfits, making it a polished choice for celebrations and evening gatherings.',
    fabricDetails: 'Light shimmer fabric with a graceful fall.',
    fit: 'Free size with fluid styling.',
    careInstructions: 'Hand wash gently. Do not wring. Dry flat in shade.',
    metaTitle: 'Dusty Rose Shimmer Hijab',
    metaDescription: 'A dusty rose shimmer hijab for partywear and festive styling.',
  },
  {
    name: 'Soft Beige Georgette Chiffon Hijab',
    slug: 'soft-beige-georgette-chiffon-hijab',
    skuPrefix: 'AMR-HJB-BGE',
    mainCategorySlug: 'hijabs',
    subcategorySlug: 'georgette-chiffon-hijabs',
    productType: 'Georgette Chiffon Hijabs',
    style: 'Hijab',
    fabric: 'Georgette',
    occasion: 'Everyday',
    colourName: 'Soft Beige',
    colourHex: '#E7D7C5',
    regularPrice: 899,
    salePrice: 699,
    stockRows: hijabStock,
    featured: false,
    newArrival: true,
    bestSeller: false,
    tags: tags(['hijab', 'georgette', 'chiffon', 'everyday', 'premium']),
    shortDescription: 'A soft beige georgette chiffon hijab with a light, elegant drape.',
    description:
      'Lightweight and refined, this soft beige georgette chiffon hijab is made for effortless modest styling. The neutral colour works across warm and cool palettes, while the airy drape keeps it comfortable for daily and semi-formal wear.',
    fabricDetails: 'Georgette chiffon with a light textured finish.',
    fit: 'Free size with airy drape.',
    careInstructions: 'Hand wash separately in cold water. Dry in shade.',
    metaTitle: 'Soft Beige Georgette Chiffon Hijab',
    metaDescription: 'A soft beige georgette chiffon hijab with an elegant lightweight drape.',
  },
];

export function buildSizes(product) {
  return sizes(product.stockRows);
}
